### PR TITLE
support for multiple extensions and filename resolves #1

### LINKED ISSUE #1: Support multiple extensions?
Hi, any chance to get support for multiple extensions? (`jsx` and `json`)?

### PR DESCRIPTION
**Pull request by lakebeach**
adds support for multiple extensions via array in options object.
also resolves filenames if they exist before trying to add index to the path.

### CODE REVIEW

**Comment by hyphaene** [comment]
Can't wait to see those changes merged ! 
Good job @lakebeach 👍

**Comment by lakebeach** [comment]
@frostney would you please have a look at this PR!

**Comment by hyphaene** [comment]
@lakebeach I would suggest you to publish your own version if there is not answer soon. If you do so, send me a message, I will update my dependencies to make it point to your package.

@frostney Please don't take my proposal personnally, this is part of the beauty of open source ;)
( or take it personnally but at least accept the pull request ;) )

Friendly,

**Comment by lakebeach** [comment]
Closing PR, will probably publish my own version on npm

**Comment by lakebeach** [comment]
@hyphaene @nikogosovd there is a new package at npm if you are still interested it has been named 'rollup-plugin-local-resolving'

**Pull request closed without merging**
